### ISSUE TITLE
Disabled folder

### ISSUE THREAD

**Issue by Ruttie2006** [fifty-six/Modinstaller2#1]
So, when the modinstaller 2 get installed it does not make a disabled folder or smth? (windows)
This causes it to give a error and makes disabling mod impossible.
https://cdn.discordapp.com/attachments/462200562620825600/845023703078010960/unknown.png
(image taken from modding-help)

**Comment by Ruttie2006** [comment]
The problem is fixed by manually making a disabled folder.

**Comment by fifty-six** [comment]
ad9516065b2e347fcde49cfefd96e7d19d96defa
